version: "3.9"

services:
  db:
    image: postgres:17                # Banco PostgreSQL versão 17
    environment:
      POSTGRES_USER: postgres         # usuário padrão
      POSTGRES_PASSWORD: postgres     # senha padrão
      POSTGRES_DB: app_development    # nome do banco inicial
    volumes:
      - pgdata:/var/lib/postgresql/data   # volume para persistir dados (não perder ao parar container)
    ports:
      - "5432:5432"                   # expõe porta do Postgres (opcional se só usar via app)

  app:
    build: .                          # constrói a imagem usando o Dockerfile atual
    depends_on:
      - db                            # garante que o banco suba antes
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app_development
    volumes:
      - .:/app                        # monta o diretório atual dentro do container (hot reload no dev)
      - bundle:/usr/local/bundle      # cache das gems instaladas
    ports:
      - "3000:3000"                   # expõe porta da API para acessar via localhost

volumes:
  pgdata:     # volume do banco
  bundle:     # volume das gems

